/*
    THIS IS A GENERATED FILE
    Changes might be overwritten in the future, edit with caution!
*/

export const Tables = {
	Users: 'Users',
	Farms: 'Farms',
	Agencies: 'Agencies',
	Quotes: 'Quotes',
	CheckoutProfiles: 'Checkout Profiles',
	ProduceType: 'Produce Type',
	Listings: 'Listings',
	ReservedListings: 'Reserved Listings',
	Notifications: 'Notifications',
	Email: 'Email',
};

export const Columns = {
	"Users": {
		username: {name:`username`, type:`text`},
		password: {name:`password`, type:`text`},
		cartIds: {name:`cart`, type:`foreignKey-many`},
		userType: {name:`user type`, type:`select`},
		contactName: {name:`contact name`, type:`text`},
		buyer_quotes: {name:`buyer_quotes`, type:`text`},
		accountApproval: {name:`account approval`, type:`select`},
		farmIdId: {name:`farm id`, type:`foreignKey-one`},
		seller_quoteIds: {name:`seller_quotes`, type:`foreignKey-many`},
		agencyIdId: {name:`agency id`, type:`foreignKey-one`},
		checkoutProfileIds: {name:`checkout profiles`, type:`foreignKey-many`},
		organization: {name:`organization`, type:`text`},
		zipcode: {name:`zipcode`, type:`number`},
		phone: {name:`phone`, type:`text`},
		additionalComments: {name:`additional comments`, type:`multilineText`},
		registrationApproval: {name:`registration approval`, type:`select`},
	},
	"Farms": {
		farmName: {name:`farm name`, type:`text`},
		description: {name:`description`, type:`multilineText`},
		listingIds: {name:`listings`, type:`foreignKey-many`},
		email: {name:`email`, type:`text`},
		phone: {name:`phone`, type:`phone`},
		farmPicture: {name:`farm picture`, type:`multipleAttachment`},
		address: {name:`address`, type:`text`},
		zipCode: {name:`zip code`, type:`number`},
		userIdId: {name:`user id`, type:`foreignKey-one`},
		market: {name:`market`, type:`multiSelect`},
		pickUpOptions: {name:`pick up options`, type:`multiSelect`},
		pacaperishableAgriculturalCommoditiesAct: {name:`PACA (Perishable Agricultural Commodities Act)`, type:`checkbox`},
		operationType: {name:`operation type`, type:`multiSelect`},
		farmingPracticeType: {name:`farming practice type`, type:`multiSelect`},
		ableToDeliver: {name:`able to deliver`, type:`checkbox`},
		coldChainCapabilities: {name:`cold chain capabilities`, type:`checkbox`},
	},
	"Agencies": {
		agencyId: {name:`agency id`, type:`formula`},
		ein: {name:`EIN`, type:`number`},
		userIdId: {name:`user id`, type:`foreignKey-one`},
		phone: {name:`phone`, type:`text`},
		email: {name:`email`, type:`text`},
		website: {name:`website`, type:`text`},
		address: {name:`address`, type:`text`},
		zipCode: {name:`zip code`, type:`number`},
		socialMedia: {name:`social media`, type:`text`},
		notes: {name:`notes`, type:`multilineText`},
		agencyName: {name:`agency name`, type:`text`},
	},
	"Quotes": {
		quoteId: {name:`quote id`, type:`formula`},
		status: {name:`status`, type:`select`},
		accepted: {name:`accepted`, type:`checkbox`},
		buyerIdIds: {name:`buyer id`, type:`foreignKey-many`},
		notificationIds: {name:`notifications`, type:`foreignKey-many`},
		initialCost: {name:`initial cost`, type:`number`},
		reservedListingIds: {name:`reserved listings`, type:`foreignKey-many`},
		createdat: {name:`createdAt`, type:`formula`},
		resolved: {name:`resolved`, type:`checkbox`},
		transportationCost: {name:`transportation cost`, type:`number`},
		processingCost: {name:`processing cost`, type:`number`},
		taxCost: {name:`tax cost`, type:`number`},
		checkoutProfileId: {name:`checkout profile`, type:`foreignKey-one`},
	},
	"Checkout Profiles": {
		profileId: {name:`profile id`, type:`formula`},
		firstName: {name:`first name`, type:`text`},
		lastName: {name:`last name`, type:`text`},
		phone: {name:`phone`, type:`text`},
		email: {name:`email`, type:`text`},
		addressLine1: {name:`address line 1`, type:`text`},
		addressLine2: {name:`address line 2`, type:`text`},
		city: {name:`city`, type:`text`},
		state: {name:`state`, type:`text`},
		country: {name:`country`, type:`text`},
		zipcode: {name:`zipcode`, type:`text`},
		quoteIdIds: {name:`quote id`, type:`foreignKey-many`},
		userIdId: {name:`user id`, type:`foreignKey-one`},
		profileName: {name:`profile name`, type:`text`},
		preferDelivery: {name:`prefer delivery`, type:`checkbox`},
		canAch: {name:`can ACH`, type:`checkbox`},
		canPaypal: {name:`can paypal`, type:`checkbox`},
		canCard: {name:`can card`, type:`checkbox`},
		canCheck: {name:`can check`, type:`checkbox`},
	},
	"Produce Type": {
		produceType: {name:`produce type`, type:`text`},
		growingGroup: {name:`growing group`, type:`multiSelect`},
		producePicture: {name:`produce picture`, type:`multipleAttachment`},
		produceCategory: {name:`produce category`, type:`select`},
		listingIdIds: {name:`listing ids`, type:`foreignKey-many`},
	},
	"Listings": {
		produceName: {name:`produce name`, type:`text`},
		farmIdId: {name:`farm id`, type:`foreignKey-one`},
		produceDetails: {name:`produce details`, type:`multilineText`},
		listingPicture: {name:`listing picture`, type:`multipleAttachment`},
		sellByDate: {name:`sell by date`, type:`date`},
		unitType1: {name:`unit type 1`, type:`select`},
		standardPricePerUnit: {name:`standard price per unit`, type:`number`},
		agencyPricePerUnit: {name:`agency price per unit`, type:`number`},
		dateEntered: {name:`date entered`, type:`date`},
		availableUntil: {name:`available until`, type:`date`},
		growingSeason: {name:`growing season`, type:`select`},
		palletsAvailable: {name:`pallets available`, type:`number`},
		palletsPending: {name:`pallets pending`, type:`number`},
		palletsSold: {name:`pallets sold`, type:`number`},
		unitsPerPallet: {name:`units per pallet`, type:`number`},
		distressed: {name:`distressed`, type:`checkbox`},
		firstAvailableDate: {name:`first available date`, type:`date`},
		reservedListingIds: {name:`reserved listings`, type:`foreignKey-many`},
		privatized: {name:`privatized`, type:`checkbox`},
		usersInterested: {name:`users interested`, type:`number`},
		produceId: {name:`produce`, type:`foreignKey-one`},
		unitType2: {name:`unit type 2`, type:`select`},
		masterUnitType: {name:`master unit type`, type:`select`},
		unitTypePerPallet: {name:`unit type per pallet`, type:`select`},
		unitType1PerUnitType2: {name:`unit type 1 per unit type 2`, type:`number`},
		unitType2PerMasterUnit: {name:`unit type 2 per master unit`, type:`number`},
		palletsPerMasterPallet: {name:`pallets per master pallet`, type:`number`},
		lbsPerUnitType2: {name:`lbs per unit type 2`, type:`number`},
		crop: {name:`crop`, type:`text`},
		expirationDate: {name:`expiration date`, type:`date`},
		lbsPerUnit: {name:`lbs per unit`, type:`number`},
		standardPricePerPallet: {name:`standard price per pallet`, type:`number`},
		unitType: {name:`unit type`, type:`select`},
		description: {name:`description`, type:`text`},
		restrictedPricePerPallet: {name:`restricted price per pallet`, type:`number`},
	},
	"Reserved Listings": {
		reservedListingId: {name:`reserved listing id`, type:`formula`},
		pallets: {name:`pallets`, type:`number`},
		userIdId: {name:`user id`, type:`foreignKey-one`},
		listingIdIds: {name:`listing id`, type:`foreignKey-many`},
		quoteIdId: {name:`quote id`, type:`foreignKey-one`},
		resolved: {name:`resolved`, type:`checkbox`},
	},
	"Notifications": {
		description: {name:`description`, type:`text`},
		buyerId: {name:`buyer id`, type:`text`},
		notificationType: {name:`notification type`, type:`select`},
		quoteIds: {name:`quote`, type:`foreignKey-many`},
	},
	"Email": {
		message: {name:`message`, type:`text`},
		email: {name:`email`, type:`text`},
		subject: {name:`subject`, type:`text`},
		lastName: {name:`last name`, type:`text`},
		phone: {name:`phone`, type:`text`},
		firstName: {name:`first name`, type:`text`},
	},
};
