/*
    THIS IS A GENERATED FILE
    Changes might be overwritten in the future, edit with caution!
*/
/* eslint-disable */ 

export const Tables = {
	Users: 'Users',
	Farms: 'Farms',
	Clusters: 'Clusters',
	Agencies: 'Agencies',
	Listings: 'Listings',
	Quotes: 'Quotes',
	ReservedListings: 'Reserved Listings',
	Notifications: 'Notifications',
};

export const Columns = {
	"Users": {
		username: {name:`username`, type:`text`},
		password: {name:`password`, type:`text`},
		cartIds: {name:`cart`, type:`foreignKey-many`},
		user_type: {name:`user_type`, type:`select`},
		display_name: {name:`display_name`, type:`text`},
		buyer_quotes: {name:`buyer_quotes`, type:`text`},
		approval: {name:`approval`, type:`select`},
		farmIds: {name:`farms`, type:`foreignKey-many`},
		seller_quoteIds: {name:`seller_quotes`, type:`foreignKey-many`},
		agencyIdIds: {name:`agency id`, type:`foreignKey-many`},
	},
	"Farms": {
		farmName: {name:`farm name`, type:`text`},
		description: {name:`description`, type:`multilineText`},
		listingIds: {name:`listings`, type:`foreignKey-many`},
		email: {name:`email`, type:`text`},
		phone: {name:`phone`, type:`phone`},
		farmPicture: {name:`farm picture`, type:`multipleAttachment`},
		address: {name:`address`, type:`text`},
		zipCode: {name:`zip code`, type:`number`},
		userIdIds: {name:`user id`, type:`foreignKey-many`},
		market: {name:`market`, type:`multiSelect`},
		pickUpOptions: {name:`pick up options`, type:`multiSelect`},
		pacaperishableAgriculturalCommoditiesAct: {name:`PACA (Perishable Agricultural Commodities Act)`, type:`checkbox`},
		operationType: {name:`operation type`, type:`multiSelect`},
		farmingPracticeType: {name:`farming practice type`, type:`multiSelect`},
		ableToDeliver: {name:`able to deliver`, type:`checkbox`},
		coldChainCapabilities: {name:`cold chain capabilities`, type:`checkbox`},
	},
	"Clusters": {
		clusterName: {name:`cluster name`, type:`text`},
		refrigeration: {name:`refrigeration`, type:`checkbox`},
		transportationOption: {name:`transportation option`, type:`select`},
		isdraft: {name:`isDraft`, type:`checkbox`},
	},
	"Agencies": {
		agencyName: {name:`agency name`, type:`text`},
		ein: {name:`EIN`, type:`number`},
		userIdId: {name:`user id`, type:`foreignKey-one`},
		phone: {name:`phone`, type:`text`},
		email: {name:`email`, type:`text`},
		website: {name:`website`, type:`text`},
		address: {name:`address`, type:`text`},
		zipCode: {name:`zip code`, type:`number`},
		socialMedia: {name:`social media`, type:`text`},
		notes: {name:`notes`, type:`multilineText`},
	},
	"Listings": {
		crop: {name:`crop`, type:`text`},
		farmIdIds: {name:`farm id`, type:`foreignKey-many`},
		description: {name:`description`, type:`multilineText`},
		listingPicture: {name:`listing picture`, type:`multipleAttachment`},
		expirationDate: {name:`expiration date`, type:`date`},
		unitType: {name:`unit type`, type:`select`},
		lbsPerUnit: {name:`lbs per unit`, type:`number`},
		standardPricePerUnit: {name:`standard price per unit`, type:`number`},
		restrictedPricePerUnit: {name:`restricted price per unit`, type:`number`},
		dateEntered: {name:`date entered`, type:`date`},
		availableUntil: {name:`available until`, type:`date`},
		growingSeason: {name:`growing season`, type:`select`},
		palletsAvailable: {name:`pallets available`, type:`number`},
		palletsPending: {name:`pallets pending`, type:`number`},
		palletsSold: {name:`pallets sold`, type:`number`},
		unitsPerPallet: {name:`units per pallet`, type:`number`},
		notes: {name:`notes`, type:`multilineText`},
		distressed: {name:`distressed`, type:`checkbox`},
		firstAvailableDate: {name:`first available date`, type:`date`},
		reservedListingIds: {name:`reserved listings`, type:`foreignKey-many`},
		privatized: {name:`privatized`, type:`checkbox`},
		usersInterested: {name:`users interested`, type:`number`},
	},
	"Quotes": {
		quoteId: {name:`quote id`, type:`formula`},
		totalCost: {name:`total cost`, type:`number`},
		status: {name:`status`, type:`select`},
		accepted: {name:`accepted`, type:`checkbox`},
		buyerIdIds: {name:`buyer id`, type:`foreignKey-many`},
		notificationIds: {name:`notifications`, type:`foreignKey-many`},
		preCost: {name:`pre cost`, type:`number`},
		reservedListingIds: {name:`reserved listings`, type:`foreignKey-many`},
		createdat: {name:`createdAt`, type:`formula`},
		resolved: {name:`resolved`, type:`checkbox`},
	},
	"Reserved Listings": {
		reservedListingId: {name:`reserved listing id`, type:`formula`},
		pallets: {name:`pallets`, type:`number`},
		userIdId: {name:`user id`, type:`foreignKey-one`},
		listingIdIds: {name:`listing id`, type:`foreignKey-many`},
		quoteIdIds: {name:`quote id`, type:`foreignKey-many`},
		resolved: {name:`resolved`, type:`checkbox`},
	},
	"Notifications": {
		description: {name:`description`, type:`text`},
		buyerId: {name:`buyer id`, type:`text`},
		notificationType: {name:`notification type`, type:`select`},
		quoteIds: {name:`quote`, type:`foreignKey-many`},
	},
};
